name: pomobunny
description: A cute Pomodoro app with a bunny companion.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/bunny.png
